import 'package:flutter/material.dart';

// Used for the pull down in the ingredients window.
List<DropdownMenuItem<String>> unitOptions = [
  const DropdownMenuItem(value: "Units", child: Text("Units")),
  const DropdownMenuItem(value: "mL", child: Text("mL")),
  const DropdownMenuItem(value: "L", child: Text("L")),
  const DropdownMenuItem(value: "dL", child: Text("dL")),
  const DropdownMenuItem(value: "teaspoon", child: Text("teaspoon")),
  const DropdownMenuItem(value: "fluid ounce", child: Text("fluid ounce")),
  const DropdownMenuItem(value: "gill", child: Text("gill")),
  const DropdownMenuItem(value: "cup", child: Text("cup")),
  const DropdownMenuItem(value: "pint", child: Text("pint")),
  const DropdownMenuItem(value: "quart", child: Text("quart")),
  const DropdownMenuItem(value: "gallon", child: Text("gallon")),
  const DropdownMenuItem(value: "mg", child: Text("mg")),
  const DropdownMenuItem(value: "g", child: Text("g")),
  const DropdownMenuItem(value: "kg", child: Text("kg")),
  const DropdownMenuItem(value: "pound", child: Text("pound")),
  const DropdownMenuItem(value: "ounce", child: Text("ounce")),
  const DropdownMenuItem(value: "pinch", child: Text("pinch")),
  const DropdownMenuItem(value: "small", child: Text("small")),
  const DropdownMenuItem(value: "medium", child: Text("medium")),
  const DropdownMenuItem(value: "large", child: Text("large")),
  const DropdownMenuItem(value: "other", child: Text("other")),
];

// Used for checking unit value to see if the units are
// custom or exist within our recommendations.
List<String> unitOptionsList = [
  "Units",
  "mL",
  "L",
  "dL",
  "tsp",
  "fl oz",
  "gill",
  "cup",
  "pint",
  "quart",
  "gal",
  "mg",
  "g",
  "kg",
  "lbs",
  "oz",
  "small",
  "med",
  "lrg",
  "other"
];

// Used for TypeAhead Widget suggestions.
// Chat GPT generated list of 100 most common ingredients.
List<String> ingrOptions = [
  "almonds",
  "allspice",
  "avocado",
  "balsamic vinegar",
  "basil",
  "bay leaves",
  "beef",
  "bell peppers",
  "black beans",
  "blue cheese",
  "butter",
  "carrots",
  "celery",
  "cheddar cheese",
  "cheese",
  "chicken",
  "chicken broth",
  "chili powder",
  "cinnamon",
  "clove",
  "coconut flakes",
  "coconut milk",
  "coriander",
  "cumin",
  "dates",
  "dijon mustard",
  "dried apricots",
  "dried cranberries",
  "dried lentils",
  "eggplant",
  "eggs",
  "fish sauce",
  "flour",
  "feta cheese",
  "garlic",
  "ginger",
  "gouda cheese",
  "gruyère cheese",
  "heavy cream",
  "honey",
  "hot sauce",
  "ketchup",
  "kidney beans",
  "leeks",
  "lemon",
  "lime",
  "mayonnaise",
  "milk",
  "mozzarella cheese",
  "mushrooms",
  "mustard",
  "nutmeg",
  "olive oil",
  "onions",
  "oregano",
  "paprika",
  "parmesan cheese",
  "parsley",
  "pecans",
  "pepper",
  "pine nuts",
  "pork",
  "poppy seeds",
  "potatoes",
  "pumpkin seeds",
  "quinoa",
  "raisins",
  "red wine",
  "rice",
  "ricotta cheese",
  "rosemary",
  "salt",
  "scallions",
  "sesame oil",
  "sesame seeds",
  "soy sauce",
  "spinach",
  "sugar",
  "sunflower seeds",
  "thyme",
  "tofu",
  "tomatoes",
  "turmeric",
  "vanilla extract",
  "vegetable broth",
  "vinegar",
  "worcestershire sauce",
  "zucchini"
];
